apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: sample-playwright
spec:
  template:
    spec:
      containers:
      - image: gretro/sample-playwright:v0.1.2
        resources:
          limits: 
            cpu: '1'
            memory: 1Gi
        startupProbe:
          httpGet:
            path: /healthz
            port: 8080
      timeoutSeconds: '60'
      serviceAccountName: playwright-sample@gossage-gretro.iam.gserviceaccount.com 
